### ISSUE TITLE
Would it be possible to have an executable for other platforms? Mainly Linux

### ISSUE THREAD

**Issue by jquievreux** [dummy-decoy/flipperzero_badusb_kl#10]

**Comment by dummy-decoy** [comment]
i modified the code in order to exclude windows specific parts when compiling on non-windows machines. makefile was modified accordingly so that you can now compile the application on linux. 
the drawback is that you can't use the dump layout (-d) option on linux, and i have no time at the moment to find an alternative way of automatically dumping keyboard mappings on linux. but you can still build a layout file manually using the -m option.

**Comment by jquievreux** [comment]
thank you very much
