### ISSUE TITLE
Why does this require a Windows computer?

### ISSUE THREAD

**Issue by suculent** [dummy-decoy/flipperzero_badusb_kl#12]
It is buildable/runnable on Mac. What is the real reason?

**Comment by RappyTV** [comment]
i think he meant if you want to use the pre-built exe

**Comment by dummy-decoy** [comment]
Thé « dump current keyboard layout » command line option uses a windows specific OS call, this option is only available on windows.
I was asked to make the software more generic so that part lies behind a compilation flag, allowing to compile the software on any platform with a compliant C compiler. 
I should update the readme to clearly state which part is windows specific.
